#!/usr/bin/python3

"""
Rectangle class representing a rectangle shape.
"""

import unittest
from models.rectangle import Rectangle


class TestRectangle(unittest.TestCase):
    """
    Test case for Rectangle class.
    """

    def test_attributes(self):
        """
        Test attribute values of a Rectangle instance.
        """
        r = Rectangle(10, 5, 2, 3, 1)
        self.assertEqual(r.width, 10)
        self.assertEqual(r.height, 5)
        self.assertEqual(r.x, 2)
        self.assertEqual(r.y, 3)
        self.assertEqual(r.id, 1)

    def test_setters(self):
        """
        Test setter methods of a Rectangle instance.
        """
        r = Rectangle(10, 5)
        r.width = 15
        r.height = 7
        r.x = 3
        r.y = 4
        self.assertEqual(r.width, 15)
        self.assertEqual(r.height, 7)
        self.assertEqual(r.x, 3)
        self.assertEqual(r.y, 4)

    def test_invalid_width(self):
        """
        Test if ValueError is raised for an invalid width.
        """
        with self.assertRaises(ValueError):
            Rectangle(-5, 5)

    def test_invalid_height(self):
        """
        Test if ValueError is raised for an invalid height.
        """
        with self.assertRaises(ValueError):
            Rectangle(10, 0)

    def test_invalid_x(self):
        """
        Test if ValueError is raised for an invalid x-coordinate.
        """
        with self.assertRaises(ValueError):
            Rectangle(10, 5, "x", 3)

    def test_invalid_y(self):
        """
        Test if ValueError is raised for an invalid y-coordinate.
        """
        with self.assertRaises(ValueError):
            Rectangle(10, 5, 2, [3])


if __name__ == '__main__':
    unittest.main()
