#!/bin/bash

# Get the Python file name from the environment variable
filename=$PYFILE
output_filename="${filename%.*}.pyc"

echo "Compiling $filename ..."
python -m py_compile $filename

if [ -f "$output_filename" ]; then
	echo "Compilation successful!"
else
	echo "Compilation failed."
fi
